ALTER TABLE applications ADD COLUMN IF NOT EXISTS cover_letter TEXT;

ALTER TABLE candidates ADD COLUMN IF NOT EXISTS skills TEXT[] DEFAULT '{}';
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS experience VARCHAR(100);
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS job_type VARCHAR(50);
